Web.Realtors.v2017/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Realtors.Controllers
{
    public class ArticleController : Controller
    {
        //Default
        public ActionResult Index()
        {
            
            return View();
            
        }

		public ActionResult AddNew()
		{
			
			return View();

		}
	}
}

Web.Realtors.v2017/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Realtors.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Web.Realtors.v2017/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;

namespace Web.Realtors.Controllers
{
    public class PropertiesController : Controller
    {
        //Default
        public ActionResult Index()
        {
            
            return View();
            
        }

		public ActionResult Update()
		{
            TestCreate();
			return View();

		}

		public ActionResult Search()
		{

			return View();

		}

        private void TestCreate()
        {
            string strCS = System.Configuration.ConfigurationManager.ConnectionStrings["CS_Web"].ConnectionString;
            SqlConnection sqlCon = new SqlConnection(strCS);
            SqlCommand sqlCom = new SqlCommand("INSERT INTO [Table_Test] ([Id],[Name])   VALUES (1,'Ovais')", sqlCon);

            sqlCom.CommandType = System.Data.CommandType.Text;

            sqlCon.Open();

            int iRowsAffeted = sqlCom.ExecuteNonQuery();

            sqlCon.Close();

        }
	}
}

Web.Realtors.v2017/Views/Article/AddNew.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="http://cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>



<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Add / Edit Articles</h1>
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Add / Edit Article
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-12">
							<form role="form" method="post" novalidate="novalidate">
								<div class="form-group">
									<label>Menu Title</label>
									<input class="form-control">
									<p class="help-block">Please enter the heading of properties(Max 50 chars).</p>
								</div>
								<div class="form-group">
									<label>Article Title</label>
									<input class="form-control">
									<p class="help-block">Please enter the heading of properties(Max 50 chars).</p>
								</div>
								
								<div class="form-group">
									<label>Priority</label>
									<select class="form-control">
										<option value="0">Select Priority</option>
										<option value="1">Top</option>
										<option value="2">Medium</option>
										<option value="3">Low</option>
										
									</select>
								</div>

								
								<div class="form-group">
									<label>Content</label>
									<textarea class="ckeditor" cols="80" id="editor1" name="editor1" rows="10"></textarea>
								</div>
								

								<button type="submit" class="btn primary_btn">Submit Article</button>
								<button type="reset" class="btn btn-default">Cancel</button>
							</form>
						</div>

					</div>
					<!-- /.row (nested) -->
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel -->
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
</div>
<!-- /#page-wrapper -->


Web.Realtors.v2017/Views/Article/Index.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">

	<div class="col-md-3">
		<p class="lead">Shop Name</p>
		<div class="list-group">
			<a href="#" class="list-group-item">Category 1</a>
			<a href="#" class="list-group-item">Category 2</a>
			<a href="#" class="list-group-item">Category 3</a>
		</div>
	</div>

	<div class="col-md-9">

		<div class="row carousel-holder">

			<div class="col-md-12">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
						<li data-target="#carousel-example-generic" data-slide-to="1"></li>
						<li data-target="#carousel-example-generic" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="item active">
							<img class="slide-image" src="http://placehold.it/800x300" alt="">
						</div>
						<div class="item">
							<img class="slide-image" src="http://placehold.it/800x300" alt="">
						</div>
						<div class="item">
							<img class="slide-image" src="http://placehold.it/800x300" alt="">
						</div>
					</div>
					<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left"></span>
					</a>
					<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right"></span>
					</a>
				</div>
			</div>

		</div>

		<div class="row">

			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$24.99</h4>
						<h4>
							<a href="#">First Product</a>
						</h4>
						<p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">15 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$64.99</h4>
						<h4>
							<a href="#">Second Product</a>
						</h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">12 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$74.99</h4>
						<h4>
							<a href="#">Third Product</a>
						</h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">31 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$84.99</h4>
						<h4>
							<a href="#">Fourth Product</a>
						</h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">6 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="http://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$94.99</h4>
						<h4>
							<a href="#">Fifth Product</a>
						</h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">18 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-4 col-md-4">
				<h4>
					<a href="#">Like this template?</a>
				</h4>
				<p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
				<a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
			</div>

		</div>

	</div>

</div>

Web.Realtors.v2017/Views/Home/Index.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">

	<div class="col-md-3">
		<p class="lead">Prime Realtors @@ 2017</p>
		<div class="list-group">
			<a href="#" class="list-group-item">Bandra West Lease 1 BHK</a>
			<a href="#" class="list-group-item">Andheri West Lease 1 BHK</a>
			<a href="#" class="list-group-item">Juhu Commercial Place</a>
		</div>
		<div class="list-group">
			<h4>
				<a href="#">Top 10 Features Of A Profitable Rental Property</a>
			</h4>
			<p>From the first decision to invest in real estate to actually buying your first rental property, there is a lot of work to be done. This task may be daunting for the first-time investor.</p>
			<a class="btn btn-primary" target="_blank" href="#">View More</a>
		</div>
		<div class="list-group">
			<h4>
				<a href="#">Tips For The Prospective Landlord</a>
			</h4>
			<p>
				Investing in rental real estate looks like a great idea on paper. You just buy a place in a nice area, find tenants and let the cash roll in.
			</p>
			<p>
				You may also like:
				<a target="_blank" href="#">Five Chart Patterns</a>
			</p>
		</div>
		<div class="list-group">
			<h4>
				<a href="#">New Ways to Profit From Renting Out Single-Family Homes</a>
			</h4>
			<p>Companies Offer Investment Options That Are Alternatives to Being a Landlord on Your Own</p>
			<a class="btn btn-primary" target="_blank" href="#">View More</a>
		</div>
		<div class="list-group">
			<h4>
				<a href="#">Flip or Hold: Best Real Estate Moves for 2015</a>
			</h4>
			<p>Whether it makes sense to flip or hold property depends entirely on your region. <a target="_blank" href="#">The big picture for 2015</a> on how to build a working review system for your online store!</p>
			<a class="btn btn-primary" target="_blank" href="#">View More</a>
		</div>
	</div>

	<div class="col-md-9">


		@Html.Partial("_LargeCarousel")


		<div class="row">



			@{
				var mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Sea facing with parking";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_01.png";
				mini.PropertyType = "1 Room Kitchen";
				mini.Ratings = 4;
				mini.TotalViews = 110;

			}

			@Html.Partial("_MiniView", mini)

			@{
                mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Sea facing with parking";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_02.png";
				mini.PropertyType = "1 BHK Apartment";
				mini.Ratings = 4;
				mini.TotalViews = 29;

			}
			@Html.Partial("_MiniView", mini)


			@{
                mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_03.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)


			@{
                mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_04.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)





			@{
				mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_05.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)


			@{
				mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_06.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)

			@{
				mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_07.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)





			@{
				mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_08.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)


			@{
				mini = new Web.Realtors.ViewModel.MiniView();
				mini.Title = "Old heritagre building";
				mini.Rent = "25,000/-";
				mini.MainImageSrc = "300x150_09.png";
				mini.PropertyType = "5 BHK Apartment";
				mini.Ratings = 5;
				mini.TotalViews = 90;

			}
			@Html.Partial("_MiniView", mini)








			@*<div class="col-sm-4 col-lg-4 col-md-4">
					<div class="thumbnail">
						<img src="http://placehold.it/320x150" alt="">
						<div class="caption">
							<h4 class="pull-right">$84.99</h4>
							<h4>
								<a href="#">Fourth Product</a>
							</h4>
							<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
						</div>
						<div class="ratings">
							<p class="pull-right">6 views</p>
							<p>
								<span class="glyphicon glyphicon-star"></span>
								<span class="glyphicon glyphicon-star"></span>
								<span class="glyphicon glyphicon-star"></span>
								<span class="glyphicon glyphicon-star-empty"></span>
								<span class="glyphicon glyphicon-star-empty"></span>
							</p>
						</div>
					</div>
				</div>*@



			@*<div class="col-sm-4 col-lg-4 col-md-4">
					<h4>
						<a href="#">Like this template?</a>
					</h4>
					<p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-More-1-building-a-review-system/">this More</a> on how to build a working review system for your online store!</p>
					<a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-More-1-building-a-review-system/">View More</a>
				</div>*@

		</div>

	</div>

</div>

Web.Realtors.v2017/Views/Home/Properties.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    Good Morning!
    </div>
</body>
</html>

Web.Realtors.v2017/Views/Properties/FormElementSample.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Forms</h1>
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Basic Form Elements
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-6">
							<form role="form">
								<div class="form-group">
									<label>Text Input</label>
									<input class="form-control">
									<p class="help-block">Example block-level help text here.</p>
								</div>
								<div class="form-group">
									<label>Text Input with Placeholder</label>
									<input class="form-control" placeholder="Enter text">
								</div>
								<div class="form-group">
									<label>Static Control</label>
									<p class="form-control-static">email@example.com</p>
								</div>
								<div class="form-group">
									<label>File input</label>
									<input type="file">
								</div>
								<div class="form-group">
									<label>Text area</label>
									<textarea class="form-control" rows="3"></textarea>
								</div>
								<div class="form-group">
									<label>Checkboxes</label>
									<div class="checkbox">
										<label>
											<input type="checkbox" value="">Checkbox 1
										</label>
									</div>
									<div class="checkbox">
										<label>
											<input type="checkbox" value="">Checkbox 2
										</label>
									</div>
									<div class="checkbox">
										<label>
											<input type="checkbox" value="">Checkbox 3
										</label>
									</div>
								</div>
								<div class="form-group">
									<label>Inline Checkboxes</label>
									<label class="checkbox-inline">
										<input type="checkbox">1
									</label>
									<label class="checkbox-inline">
										<input type="checkbox">2
									</label>
									<label class="checkbox-inline">
										<input type="checkbox">3
									</label>
								</div>
								<div class="form-group">
									<label>Radio Buttons</label>
									<div class="radio">
										<label>
											<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>Radio 1
										</label>
									</div>
									<div class="radio">
										<label>
											<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Radio 2
										</label>
									</div>
									<div class="radio">
										<label>
											<input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">Radio 3
										</label>
									</div>
								</div>
								<div class="form-group">
									<label>Inline Radio Buttons</label>
									<label class="radio-inline">
										<input type="radio" name="optionsRadiosInline" id="optionsRadiosInline1" value="option1" checked>1
									</label>
									<label class="radio-inline">
										<input type="radio" name="optionsRadiosInline" id="optionsRadiosInline2" value="option2">2
									</label>
									<label class="radio-inline">
										<input type="radio" name="optionsRadiosInline" id="optionsRadiosInline3" value="option3">3
									</label>
								</div>
								<div class="form-group">
									<label>Selects</label>
									<select class="form-control">
										<option>1</option>
										<option>2</option>
										<option>3</option>
										<option>4</option>
										<option>5</option>
									</select>
								</div>
								<div class="form-group">
									<label>Multiple Selects</label>
									<select multiple class="form-control">
										<option>1</option>
										<option>2</option>
										<option>3</option>
										<option>4</option>
										<option>5</option>
									</select>
								</div>
								<button type="submit" class="btn btn-default">Submit Button</button>
								<button type="reset" class="btn btn-default">Reset Button</button>
							</form>
						</div>
						<!-- /.col-lg-6 (nested) -->
						<div class="col-lg-6">
							<h1>Disabled Form States</h1>
							<form role="form">
								<fieldset disabled>
									<div class="form-group">
										<label for="disabledSelect">Disabled input</label>
										<input class="form-control" id="disabledInput" type="text" placeholder="Disabled input" disabled>
									</div>
									<div class="form-group">
										<label for="disabledSelect">Disabled select menu</label>
										<select id="disabledSelect" class="form-control">
											<option>Disabled select</option>
										</select>
									</div>
									<div class="checkbox">
										<label>
											<input type="checkbox">Disabled Checkbox
										</label>
									</div>
									<button type="submit" class="btn btn-primary">Disabled Button</button>
								</fieldset>
							</form>
							<h1>Form Validation States</h1>
							<form role="form">
								<div class="form-group has-success">
									<label class="control-label" for="inputSuccess">Input with success</label>
									<input type="text" class="form-control" id="inputSuccess">
								</div>
								<div class="form-group has-warning">
									<label class="control-label" for="inputWarning">Input with warning</label>
									<input type="text" class="form-control" id="inputWarning">
								</div>
								<div class="form-group has-error">
									<label class="control-label" for="inputError">Input with error</label>
									<input type="text" class="form-control" id="inputError">
								</div>
							</form>
							<h1>Input Groups</h1>
							<form role="form">
								<div class="form-group input-group">
									<span class="input-group-addon">@@</span>
									<input type="text" class="form-control" placeholder="Username">
								</div>
								<div class="form-group input-group">
									<input type="text" class="form-control">
									<span class="input-group-addon">.00</span>
								</div>
								<div class="form-group input-group">
									<span class="input-group-addon">
										<i class="fa fa-eur"></i>
									</span>
									<input type="text" class="form-control" placeholder="Font Awesome Icon">
								</div>
								<div class="form-group input-group">
									<span class="input-group-addon">$</span>
									<input type="text" class="form-control">
									<span class="input-group-addon">.00</span>
								</div>
								<div class="form-group input-group">
									<input type="text" class="form-control">
									<span class="input-group-btn">
										<button class="btn btn-default" type="button">
											<i class="fa fa-search"></i>
										</button>
									</span>
								</div>
							</form>
						</div>
						<!-- /.col-lg-6 (nested) -->
					</div>
					<!-- /.row (nested) -->
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel -->
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
</div>
<!-- /#page-wrapper -->

Web.Realtors.v2017/Views/Properties/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    Good Morning!
    </div>
</body>
</html>

Web.Realtors.v2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
	<!--Favicon-->
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/font-awesome.min.css" rel="stylesheet" />
	<link href="~/css/StyleHome.css" rel="stylesheet" />
</head>
<body>


	@Html.Partial("_header")



	<!-- Page Content -->
	<div class="container">

		@RenderBody()

	</div>







	@Html.Partial("_footer")


</body>
</html>

Web.Realtors.v2017/Views/Shared/_MiniView.cshtml
@model Web.Realtors.ViewModel.MiniView

<div class="col-sm-4 col-lg-4 col-md-4">
	<div class="thumbnail">
		<img src="~/CommonImages/@Model.MainImageSrc" alt="">
		<div class="caption">
			<h4 class="pull-right">Rs. @Model.Rent</h4>
			<h4>
				<a href="#">@Model.PropertyType</a>
			</h4>
			<p>@Model.Title <a target="_blank" href="http://www.bootsnipp.com">Bandra West</a>.</p>
			
		</div>
		<div class="ratings">
			<p class="pull-right">@Model.TotalViews views</p>
			<p>
				@for (int iCtr = 0; iCtr < Model.Ratings; iCtr++)
				{
					<span class="glyphicon glyphicon-star"></span>
				}

				@for (int iCtr = Model.Ratings; iCtr < 5; iCtr++)
				{
					<span class="glyphicon glyphicon-star-empty"></span>
				}
				
				
				
			</p>
		</div>
	</div>
</div>

Web.Realtors.v2017/Views/Shared/_header.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="@Url.Action("", "")">PrimeRealtors</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<a href="@Url.Action("Update", "Properties")">Add New Properties</a>
				</li>
				<li>
					<a href="@Url.Action("AddNew", "Article")">Add New Article</a>
				</li>
				<li>
					<a href="#">Contact</a>
				</li>
				
			</ul>
			<div class="col-sm-6 col-md-6 pull-right">
				<form class="navbar-form" role="search" action="@Url.Action("Search", "Properties")" method="get">
					<div class="input-group col-sm-3">						
						<select class="form-control" name="type">
							<option value="0">Property Type</option>
							<option value="1">Residential - 1BHK</option>
							<option value="2">Residential - 2BHK</option>
							<option value="3">Residential - 3BHK</option>
							<option value="4">Residential - 4BHK</option>
							<option value="5">Commercial - Office</option>
							<option value="6">Commercial - Shop</option>
							<option value="7">Commercial - Godown</option>
							<option value="8">PG</option>
						</select>
					</div>
					<div class="input-group col-sm-3">
						<select class="form-control "  name="locality">
							<option value="0">Locality</option>
							<option value="1">Bandra W</option>
							<option value="2">Bandra E</option>
							<option value="3">Bandra BKC</option>
							<option value="4">Andheri - E</option>
							<option value="5">Andheri - W</option>
							<option value="6">Juhu</option>
							<option value="7">Santacruz - E</option>
							<option value="8">Santacruz - W</option>
							<option value="9">Khar - W</option>
							<option value="10">Khar - E</option>
						</select>

					</div>
					<div class="input-group col-sm-3">
						<input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
						<div class="input-group-btn">
							<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>